# Generated by Django 5.2.9 on 2026-09-16 21:48

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(default=home.models.generate_short_id, editable=False, max_length=12, unique=True)),
                ('quote_text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('quote_text', 'author'), name='unique_shared_quote')],
            },
        ),
    ]
