# Generated by Django 5.2.9 on 2026-06-06 06:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'quote_text', 'author')},
        ),
    ]
